apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc-rwx
  namespace: sock-shop
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  storageClassName: csi-cephfs
